### ISSUE TITLE
Can no longer access or edit LCDs directly

### ISSUE THREAD

**Issue by wilki24** [viktor-ferenczi/performance-improvements#28]
Unfortunately pull 1.10.0 #27 has caused an issue with accessing LCDs. I've isolated it to this plugin.
Steps to repro:
1. Start a fresh custom game. I choose survival in a star system.
2. Turn on creative mode tools in the alt-f10 admin tools menu.
3. Place any LCD on the side of your drop pod.
4. Aim at the LCD and press K. You will get a notification that the panel is read only. You can access it from other control panels, but never directly. This also prevents you from editing it.

Thanks!

**Comment by viktor-ferenczi** [comment]
Fixed in 1.10.1

Tested OK in single player following the above steps.
