### ISSUE TITLE
IMyShipConnector.OtherConnector or .OtherConnector.CubeGrid returns null

### ISSUE THREAD

**Issue by skullbearer** [viktor-ferenczi/performance-improvements#36]
This is specific to PB API calls for IMyShipConnector.OtherConnector or IMyShipConnector.OtherConnector.CubeGrid, which are common in inventory accessing scripts such as IIM.

The issue occurs when a grid is connected via a connector and either (we can't determine which) the conveyor or the groups patch option is selected.

Removing both of them resolved the issue and it has not returned even when we enabled them one at a time and together, however, it persisted through dozens of server restarts. We'll add to this issue if it returns.

My GUESS is that the thread priority change for MyCubeGrid.MergeGroups() is conflicting with the MyShipConnector.TryAttach and ultimately with CreateConstraint()'s Sync call returning that the connectors have a constraint and are connected, but returning null in the otherConnectorCubGrid (this is again, my guess) due to the MergeGroups() shift off of the main thread.

Unable to reliably replicate, is fixed by one or both of the conveyor and group patches being disabled. Does not return when enabling them while server is live. Have not gone through a restart to confirm the issue returns after restart with them enabled. Will update further. Issue is that when problem exists, IMyShipConnector.OtherConnector or .OtherConnector.CubeGrid is null. Grid shows valid connection and works through control panel, this is exclusive to PB API call.

**Comment by viktor-ferenczi** [comment]
What was the exact problem? Crash inside the PerformanceImprovements plugin?

If crash, the could you please attach a stack trace (or even better a full log)?

Server or client?

**Comment by skullbearer** [comment]
No crash on the server or the plugin or client. This is returning null to the PB API call for IMyShipConnector.OtherConnector or IMyShipConnector.OtherConnector.CubeGrid.

**Comment by viktor-ferenczi** [comment]
Try to disable the **Fix grid merge** fix in the plugin config.

What it does may be related to your issue: "Disable conveyor updates during grid merge (MyCubeGrid.MergeGridInternal)"

Does it solve your problem? If not, then please try to disable half of the remaining tests each time and narrow down which one is causing the issue.

The workaround is to keep that fix (or fixes) disabled.

**Comment by skullbearer** [comment]
We did disable that performance patch (the conveyor updates) and it did seem to resolve the issue, even after the patch was re-enabled. We've been unable to replicate it, but that it was immediately corrected upon toggling that option implies a causal link. Why it doesn't return, we don't know. We did other, unrelated to your plugin things, to dramatically improve simspeed, so it could be that the worker threads are completing in the same tick reliably enough that the problem is not occurring. Connecting two grids during low simspeed may replicate it.

**Comment by viktor-ferenczi** [comment]
> We did other, unrelated to your plugin things, to dramatically improve simspeed

What else have you configured exactly to improve performance? Maybe it gives some clue.

**Comment by skullbearer** [comment]
Cleaned up grid clusters, hangared a lot of grids. Nothing that would be related other than to simspeed.

The problem has returned so we're trying to sync up with a player experiencing it to try and confirm which plugin setting is causing it. Personally I do not think that the conveyor during merge would be the cause because the affected Keen code only occurs when a full grid merge occurs, such as with a merge block or a copy-paste of a grid onto another grid.

**Comment by viktor-ferenczi** [comment]
Thank you for narrowing this issue down to a specific config option.

**Comment by viktor-ferenczi** [comment]
Does this issue still happen with game version 1.203.022?
